# Generated by Django 5.0.8 on 2024-08-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_migrate_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
