version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.3

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_docker_image:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: docker build -t my-dockerhub-user/my-app:latest .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push my-dockerhub-user/my-app:latest

  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to Render
          command: |
            curl -X POST https://api.render.com/v1/services/YOUR_SERVICE_ID/deploys \
            -H 'Authorization: Bearer YOUR_API_KEY' \
            -H 'Content-Type: application/json' \
            -d '{"clearCache": false}'

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - build_docker_image:
          requires:
            - build_and_test
      - deploy:
          requires:
            - build_docker_image
          filters:
            branches:
              only: main
