version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.3
jobs:
  build_and_test:
    docker:
            - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy
          command: echo "Deploying the project"

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
