version: 2.1

orbs:
  python: circleci/python@2.0.3
  docker: circleci/docker@2.1.3

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  build_docker_image:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: docker build -t $DOCKERHUB_USERNAME/my-app:latest .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push $DOCKERHUB_USERNAME/my-app:latest
  collect_static_files:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Collect static files
          command: |
            docker run --rm \
            -v $PWD:/app \
            -w /app \
            $DOCKERHUB_USERNAME/my-app:latest \
            python manage.py collectstatic --noinput

  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to Render
          command: |
            curl -X POST https://api.render.com/deploy/$RENDER_SITE_URL?key=$RENDER_API_KEY \
            -H 'Authorization: Bearer $RENDER_API_KEY' \
            -H 'Content-Type: application/json' \
            -d '{"image": "docker.io/$DOCKERHUB_USERNAME/my-app:latest", "clearCache": false}'
      
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - build_docker_image:
          requires:
            - build_and_test
      - collect_static_files:
          requires:
            - build_docker_image
      - deploy:
          requires:
            - collect_static_files
          filters:
            branches:
              only: etape-4
